all: stack queue BSTtoLinkedList LinkedListToBST 

stack: stack.cpp
	g++ -Wall -o stack stack.cpp

queue: queue.cpp
	g++ -Wall -o queue queue.cpp

BSTtoLinkedList: BSTtoLinkedList.cpp 
	g++ -Wall -o BSTtoLinkedList BSTtoLinkedList.cpp

LinkedListToBST: LinkedListToBST.cpp
	g++ -Wall -o LinkedListToBST LinkedListToBST.cpp

clean:
	rm stack queue BSTtoLinkedList LinkedListToBST 