all: a2p1 a2p2 a2p3 a2p4 a2p5 a2p6

a2p1: a2_p1.cpp
	g++ -Wall -o a2p1 a2_p1.cpp

a2p2: a2_p2.cpp
	g++ -Wall -o a2p2 a2_p2.cpp

a2p3: WindGauge.cpp testWindGauge.cpp WindGauge.h
	g++ -Wall -o a2p3 WindGauge.cpp testWindGauge.cpp

a2p4: a2_p4.cpp
	g++ -Wall -o a2p4 a2_p4.cpp

a2p5: a2_p5.cpp
	g++ -Wall -o a2p5 a2_p5.cpp

a2p6: a2_p6.cpp
	g++ -Wall -o a2p6 a2_p6.cpp

clean:
	rm a2p1 a2p2 a2p3 a2p4 a2p5 a2p6