all: a1p1 a1p2 a1p3 a1p4 a1p5

a1p1: a1_p1.cpp
	g++ -Wall -o a1p1 a1_p1.cpp

a1p2: testStack.cpp Stack.h
	g++ -Wall -o a1p2 testStack.cpp

a1p3: testLinkedList.cpp LinkedList.h
	g++ -Wall -o a1p3 testLinkedList.cpp

a1p4: a1_p4.cpp
	g++ -Wall -o a1p4 a1_p4.cpp

a1p5: a1_p5.cpp
	g++ -Wall -o a1p5 a1_p5.cpp

clean:
	rm a1p1 a1p2 a1p3 a1p4 a1p5