all: QuickSort DualPivotQuickSort

QuickSort: QuickSort.cpp
	g++ -Wall -o QuickSort QuickSort.cpp

DualPivotQuickSort: DualPivotQuickSort.cpp
	g++ -Wall -o DualPivotQuickSort DualPivotQuickSort.cpp

clean:
	rm QuickSort DualPivotQuickSort