all: CountingSort BucketSort WordSort RadixSort 

CountingSort: CountingSort.cpp
	g++ -Wall -o CountingSort CountingSort.cpp

BucketSort: BucketSort.cpp
	g++ -Wall -o BucketSort BucketSort.cpp

WordSort: WordSort.cpp 
	g++ -Wall -o WordSort WordSort.cpp 

RadixSort: RadixSort.cpp 
	g++ -Wall -o RadixSort RadixSort.cpp

clean:
	rm CountingSort BucketSort WordSort RadixSort