all: HeapSort BottomUpHeapSort

HeapSort: HeapSort.cpp
	g++ -Wall -o HeapSort HeapSort.cpp

BottomUpHeapSort: BottomUpHeapSort.cpp
	g++ -Wall -o BottomUpHeapSort BottomUpHeapSort.cpp

clean:
	rm HeapSort BottomUpHeapSort